<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Wallet;
use Doctrine\DBAL\Types\Type;
use League\Period\Period;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriod(Wallet $wallet, Period $period)
    {
        return $this->getEntityManager()
            ->createQuery('
                  SELECT e
                  FROM AppBundle:Income e 
                  WHERE e.wallet = :wallet 
                    AND (e.createdAt BETWEEN :start AND :finish)
                  ORDER BY e.createdAt ASC
              ')->setParameter('wallet', $wallet)
            ->setParameter('start', $period->getStartDate(), Type::DATETIME)
            ->setParameter('finish', $period->getEndDate(), Type::DATETIME)
            ->getResult();
    }
}
