imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: php
#        result_cache_driver: php
#        query_cache_driver: php

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      rollbar
        rollbar:
            type:  rollbar
            level: error
            token: %rollbar_token%
            config:
                environment: %rollbar_environment%
        console:
            type:  console

knp_snappy:
    pdf:
        enabled:    true
        binary:     "%app_wkhtmltopdf_binary%"
        options:
        - { name: 'viewport-size', value: '1024x768' }
        - { name: 'page-size', value: 'A4' }
