<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160515201825 extends AbstractMigration
{


    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE bots ADD token VARCHAR(128) NOT NULL DEFAULT "", ADD botan_token VARCHAR(128) DEFAULT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
    }

    public function postUp(Schema $schema)
    {
        parent::postUp($schema); // TODO: Change the autogenerated stub
    }


    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE bots DROP token, DROP botan_token, CHANGE updated_at updated_at DATETIME NOT NULL');
    }
}
